### ISSUE TITLE
Problems with some GUI elements

### ISSUE THREAD

**Issue by Senliast** [Snudgee/Pure#15]
Screenshots are attached, the problem is visible here. If you have time to fix it - it would be great. Thank you!

https://imgur.com/a/tffr3xh

**Comment by Senliast** [comment]
Also one more issue with announcements, when its there: https://imgur.com/a/s2f7t8w

**Comment by Vrime** [comment]
в папке с темами есть папка FONTS, зайди в неё, и скачай шрифты оттуда

**Comment by Senliast** [comment]
> в папке с темами есть папка FONTS, зайди в неё, и скачай шрифты оттуда

так сделал же

**Comment by Senliast** [comment]
Solved
