### ISSUE TITLE
friends UI doesent work

### ISSUE THREAD

**Issue by Metalism666** [Snudgee/Pure#21]
![image](https://user-images.githubusercontent.com/87187521/158390548-0d092ceb-f5c1-478f-b0e4-9c7f0466f2dc.png)
 
in the guide: * open steamfriendspatcher and go to settings set the library css to 7.css, click save settings and force check  *
 
i dont have 7.css so i set 6.ss , the library work fine , but friends ui dosent work

**Comment by InsulateJustf** [comment]
The same here😂

**Comment by Snudgee** [comment]
the friends ui rarely ever gets patched properly sadly 😥
