### ISSUE TITLE
Library interface does not match Pure (Dark) skin.

### ISSUE THREAD

**Issue by Mr-Terminal** [Snudgee/Pure#23]
Hello. I've recently installed Pure (Dark) for Steam but the Library interface does not match the skin. I've installed the files per instruction, I ran Steam Friends Patcher, I've restarted Steam multiple times and I've restarted the computer once. Nothing seems to work.

Here's what I'm seeing right now:
<img width="960" alt="2022-04-05" src="https://user-images.githubusercontent.com/53662823/161682141-6f08c380-e52d-417c-8c3c-91e6f8001540.png">

I've tried clearing the Steam cache through the Patcher multiple times. It gave me this warning:
![image](https://user-images.githubusercontent.com/53662823/161683397-6c095e17-ed39-4c27-a1b6-3e02a9aa94a5.png)

I hope there's a fix soon, as I wanted to have a dark mode skin for Steam, but the inconsistency doesn't give me the full satisfaction that I want. Thank you.

**Comment by Snudgee** [comment]
use the libraryrootcustom.css file from the dark folder
